### PR TITLE
Fix broken tracing UI

### PR DESCRIPTION
**Pull request by PavelGavlik**
- missing prop was preventing rendering of tracing results
- Message "Please re-run the query to show tracing results." was shown even though results were available

### CODE REVIEW

**Comment by PavelGavlik** [comment]
Thank you for merging this so quickly!

**Comment by lookapanda** [comment]
Hey, I just noticed this bug in my local installation of Playground, update check says there is no update so I assume this hasn't been pushed yet. Any ETA?

**Comment by Huvik** [comment]
@lookapanda 1-2 days :) We will release it after we merge #733

**Comment by benwaffle** [comment]
I'm on v1.6.1 and this bug does not seem to be fixed.

**Pull request merged**
